### ISSUE TITLE
Unexpected commas 

### ISSUE THREAD

**Issue by Keithsc** [LinOTP/LinOTP#10]
Hi, I am having some trouble getting LinOTP installed on Centos7. Using a combination of the instructions on the LinOTP site and a few modifications to the python pip modules versions available I have been able to start the server. I can start the server but there seems to be an issue with strings being broken up into comma separated characters. (see Below)

I had to modify the requires.txt file as I was unable to find some of the module versions that were required.

{
   "version": "LinOTP 2.7.1.2", 
   "jsonrpc": "2.0", 
   "result": {
      "status": false, 
      "error": {
         "message": "Illegal key value: a,d,m,i,n,_,s,e,s,s,i,o,n,", 
         "code": -311
      }
   }, 
   "id": 1
}

/opt/LINOTP/lib/python2.7/site-packages/LinOTP-2.7.1.2-py2.7.egg-info/requires.txt
Pylons>=0.9.7,<=1.0.1           was <1.1
WebOb<1.5                            was <1.4
SQLAlchemy>=0.6
docutils>=0.4
simplejson>=2.0
pycrypto>=1.0
repoze.who<=3.1                   was <1.1
pyrad>=1.1
LinOtpUserIdResolver>=2.7.dev
netaddr
qrcode>=2.4
configobj>=4.6.0
httplib2
sqlalchemy-migrate

CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: 't,e,x,t,/,h,t,m,l,,,a,p,p,l,i,c,a,t,i,o,n,/,x,h,t,m,l,+,x,m,l,,,a,p,p,l,i,c,a,t,i,o,n,/,x,m,l,;,q,=,0,.,9,,,*,/,*,;,q,=,0,.,8'
  HTTP_ACCEPT_ENCODING: 'g,z,i,p,,, ,d,e,f,l,a,t,e'
  HTTP_ACCEPT_LANGUAGE: 'e,n,-,U,S,,,e,n,;,q,=,0,.,5'
  HTTP_CONNECTION: 'k,e,e,p,-,a,l,i,v,e'
  HTTP_COOKIE: 'a,d,m,i,n,_,s,e,s,s,i,o,n,=,8,5,f,7,d,1,0,2,b,d,1,9,9,e,a,5,7,1,e,0,6,d,6,a,4,e,b,2,9,3,0,0,5,a,a,6,4,5,a,0,6,2,3,f,f,2,2,6,e,5,b,d,2,c,8,c,0,8,f,9,6,d,5,6'
  HTTP_DNT: '1'
  HTTP_HOST: '1,9,2,.,1,6,8,.,xxxx,.,xx,:,5,0,0,1'
  HTTP_USER_AGENT: 'M,o,z,i,l,l,a,/,5,.,0, ,(,W,i,n,d,o,w,s, ,N,T, ,6,.,1,;, ,W,O,W,6,4,;, ,r,v,:,3,7,.,0,), ,G,e,c,k,o,/,2,0,1,0,0,1,0,1, ,F,i,r,e,f,o,x,/,3,7,.,0'
  PATH_INFO: '/account/login'
  REMOTE_ADDR: '192.168.xx.xxx'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '5001'
  SERVER_PROTOCOL: 'HTTP/1.1'

WSGI Variables
--------------
  application: <beaker.middleware.CacheMiddleware object at 0x4275e50>
  beaker.cache: <beaker.cache.CacheManager object at 0x4275e90>
  beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x4275910>>
  beaker.session: Cannot display: Illegal key value: a,d,m,i,n,_,s,e,s,s,i,o,n,
  paste.cookies: (<SimpleCookie: >, 'a,d,m,i,n,_,s,e,s,s,i,o,n,=,8,5,f,7,d,1,0,2,b,d,1,9,9,e,a,5,7,1,e,0,6,d,6,a,4,e,b,2,9,3,0,0,5,a,a,6,4,5,a,0,6,2,3,f,f,2,2,6,e,5,b,d,2,c,8,c,0,8,f,9,6,d,5,6')
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x2a1fdd0>
  paste.registry: <paste.registry.Registry object at 0x7fd1dc2b7fd0>
  paste.throw_errors: True
  pylons.controller: <linotp.controllers.account.AccountController object at 0x7fd1dc2bb2d0>
  pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
  pylons.log_debug: True
  pylons.pylons: <pylons.util.PylonsContext object at 0x7fd1dc2bb250>
  pylons.routes_dict: {'action': u'login', 'controller': u'account'}
  repoze.who.api: <repoze.who.api.API object at 0x7fd1dc2b7dd0>
  repoze.who.logger: <logging.Logger object at 0x42bb090>
  repoze.who.plugins: {'linotp.lib.repoze_auth:UserModelPlugin': <linotp.lib.repoze_auth.UserModelPlugin object at 0x42b1f90>, 'auth_tkt': <AuthTktCookiePlugin 69931728>, 'form': <RedirectingFormPlugin 69931600>}
  routes.route: <routes.route.Route object at 0x3a37ad0>
  routes.url: <routes.util.URLGenerator object at 0x7fd1dc2bb0d0>
  wsgi process: 'Multithreaded'
  wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7fd1dc2bb0d0>, {'action': u'login', 'controller': u'account'})

I'd prefer to use Centos7 as the base OS but If nessacery I am prepared to use a supported OS.
Thanks
Keith.

**Comment by lse-christian** [comment]
Hi,
this issue is related to Python Paste version 2.0.1. Upgrading to Paste 2.0.2 via 'pip install --upgrade paste' should solve the problem.
You can find more information on this bug in the Paste bug tracker: https://bitbucket.org/ianb/paste/issue/4/wsgi-environ-totally-borked

Please feel free to reopen your ticket if upgrading paste does not fix the issue.
Cheers!
Christian
Hi,
this issue is related to Python Paste version 2.0.1. Upgrading to Paste 2.0.2 via 'pip install --upgrade paste' should solve the problem.
You can find more information on this bug in the Paste bug tracker: https://bitbucket.org/ianb/paste/issue/4/wsgi-environ-totally-borked

Please feel free to reopen your ticket if upgrading paste does not fix the issue.
Cheers!
Christian

**Comment by Keithsc** [comment]
Hi,
Thanks for the speedy response. upgrading 'paste' has resolved this problem.

Thanks
Keith
