### ISSUE TITLE
Dockerfile - COPY failed

### ISSUE THREAD

**Issue by RazviAlex** [LinOTP/LinOTP#112]
Hi,

When I try to build an image from the Dockerfile: 
`sudo docker build -t linotp:latest --file Dockerfile . `

It gives the following error:
```
Step 10/20 : COPY apt /opt/linotp/apt
COPY failed: stat /var/lib/docker/tmp/docker-builder251462879/apt: no such file or directory
```
And the image gets corrupted..
![image](https://user-images.githubusercontent.com/51793648/59445653-51800780-8e00-11e9-985b-7cc3b1f25625.png)

Anyone have any idea of what is wrong? Or have a doc/guide of how to install linotp through docker?

Thank you!

**Comment by challs** [comment]
Hi
The Docker build process needs to have prebuilt packages available to install. It's basically the [Docker multi-stage build / Builder pattern](https://docs.docker.com/develop/develop-images/multistage-build/), but it was written before Docker had native support for such a pattern. You can trigger the build process by running `make docker-build-all` from the project root. This will use a separate Docker image to create the .deb packages, which can then be installed into the linotp image.

**Comment by RazviAlex** [comment]
It works! Thank you @challs
