### ISSUE TITLE
Debian buster: Support for Debian buster is missing

### ISSUE THREAD

**Issue by disaster123** [LinOTP/LinOTP#115]
Debian Buster was released last month. It would be great to support a current debian stable release.

**Comment by jdelvecchio** [comment]
Indeed, that would be great, the page https://linotp.org/doc/latest/part-installation/server-installation/deb_install.html only lists jessie and stretch as installation options.

**Comment by authprivsec** [comment]
We are working on having a release for buster ready Soon™  (this year if things go as planned). This also involves some of our products around LinOTP so it takes more time than expected in some areas.

The development team is also working hard on porting LinOTP to Flask and Python3. There will be a release available later this year, based on Flask and Python3 (and buster) which is based on the current LinOTP 2.X release and there will be a LinOTP 3.X in the beginning of 2020 which will bring additional changes to functionality and workflows. 

So if we are a bit silent here it is not for a lack of interest, we are just all extremely busy to bring things up to standard again.

**Comment by zsoltbarat** [comment]
Hi there,
any news about the buster release or LinOTP 3.x for Python3.
Python2 is already deprecated.
Whats the preferred installation method beside the distro packages?
The version which get installed with pip is 2.10.01, which seems pretty old.

**Comment by megfault** [comment]
Hi @zsoltbarat 

There is this branch with Python3: https://github.com/LinOTP/LinOTP/tree/branch-v2.90
A proper release is coming soon.

I cannot help you with the installation, though. Hopefully someone else will :-)

**Comment by zsoltbarat** [comment]
Hi @megfault 
any news about the proper release. I just saw that you are preparing 2.11.1. What about this release?
Is there this more preferable than 2.90?

**Comment by zsoltbarat** [comment]
hello @megfault are you still there?

**Comment by megfault** [comment]
Hi @zsoltbarat I am still here :-)

2.11 is a Python 2 release. 2.90 is a fork we made to start porting LinOTP to Python 3 in parallel to a few bugfixes to version 2. I know the branch names are not very helpful, sorry about that. So please stick to 2.90 if you want Python 3.

**Comment by megfault** [comment]
@disaster123  @jdelvecchio there is a Debian Buster release for LinOTP 2.11.1 now. I am closing this issue.
