### ISSUE TITLE
JQuery vulnerability

### ISSUE THREAD

**Issue by lukas-lew** [LinOTP/LinOTP#123]
We have an issue with passing security scans due to below vulnerability:

**124719 (1) - JQuery < 3.4.0 Object Prototype Pollution Vulnerability**
**Synopsis**
The remote web server is affected by an object pollution vulnerability.
**Description**
The version of JQuery library hosted on the remote web server is prior to 3.4.0. It is, therefore, affected by an object
pollution vulnerability in jQuery.extend(true, {}, ...) because of Object.prototype pollution. If an unsanitized source
object contained an enumerable __proto__ property, it could extend the native Object.prototype.

URL : https://XXXXXXX/js/jquery-1.12.4.min.js
Installed version : 1.12.4
Fixed version : 3.4.0

Any advise ?

**Comment by authprivsec** [comment]
Thank you for your report. We are looking into the situation and will get back to you with possible solutions.

**Comment by lukas-lew** [comment]
Thank you @authprivsec !
Awaiting updates.

**Comment by lukas-lew** [comment]
Thanks for all your work. 

Do we have any updates regarding the upgrade path to migrate to jQuery version 3.4 ?

**Comment by lukengda** [comment]
Branch `branch-v2.11` is already based on jQuery version 3.4.1. The changes are currently scheduled for LinOTP version 2.11.1 and will get merged into master.

I will close this issue here as your original issue is therefore resolved.
