### ISSUE TITLE
Does the latest stable version support Python 3.x ?

### ISSUE THREAD

**Issue by luckydogxf** [LinOTP/LinOTP#124]
Hi, as we know, python 2.7 will close to an end of its lifecycle, and would be deprecated on 2020/1/1.

Does the latest stable version support Python 3.x ? I checked the documentation and found that LinOTP is well tested with Python 2.7. 

Maybe this doc was not updated.

So does anyone know the answer? And how to upgrade it to support python 3.x ?

Just use pip or something to install Python 3.x and keep the old code  or upgrade both python  and source code together?

Thanks.

**Comment by megfault** [comment]
Hello, and thank you for the questions. I am sure there are more people out there wondering the same as you.

The latest version does not yet support Python 3. Just using Python 3 with the old code will definitely not work.

My team is currently working on a Python 3 port, and we are aiming for the end of the year.

**Comment by megfault** [comment]
I am closing this issue, as there seems to be no further questions.
