### ISSUE TITLE
Gemalto convert error (no module named pbkdf2)

### ISSUE THREAD

**Issue by sverslaagh** [LinOTP/LinOTP#125]
Hi all, 

When running linotp/linotpd/src/tools# ./linotp-convert-gemalto I'm getting the message that the module pbkdf2 cannot be found while I installed it through pip, pip3 and apt (python-pbkdf2). 

Any help on how I can address this?

root@ubuntu:/home/sjon/linotp/linotpd/src/tools# ./linotp-convert-gemalto
Traceback (most recent call last):
  File "./linotp-convert-gemalto", line 43, in <module>
    import linotp.lib.pbkdf2 as pbkdf2
ImportError: No module named pbkdf2
root@ubuntu:/home/sjon/linotp/linotpd/src/tools#

Also tried pip install linotp. Went successfully but still can't use the program.

**Comment by megfault** [comment]
Oops, clicked close by mistake :o)
