### ISSUE TITLE
Multiple realms while assigning

### ISSUE THREAD

**Issue by softstraus** [LinOTP/LinOTP#128]
LinOTP 2.10.5.3 
I have two realms. When assign token for user - only one of them can be added.
Second realm I must add manually.
Is it way to add both realms at once while "assign" ?

**Comment by megfault** [comment]
Hello @softstraus 

A user can indeed exist in two realms, but a token can only be assigned to a user in the context of one realm. If the token has no user, it can be it in two realms, but as soon as you assign it to a user, it will only be in one of the realms. That means that your second realm assignment should invalidate the first.
