### ISSUE TITLE
Linotp LDAP Proxy not encoding username and password

### ISSUE THREAD

**Issue by danilotaveira** [LinOTP/LinOTP#129]
If the user password has some special characters like % followed by numbers when the password is sent to the LinOTP API for validation it is not recognized because %nn is decoded by the API.

The following line in LinotpLDAPProxy.pm sends the user and password without any previous encoding

my $url = "https://localhost/validate/check?user=$username&pass=$bindpw";

**Comment by megfault** [comment]
You are right. Either we have to URL-encode, or we send the values in the body of a POST request. Thanks for the issue report, we'll have a look.
