### ISSUE TITLE
PyPi releases are not up to date

### ISSUE THREAD

**Issue by aneutron** [LinOTP/LinOTP#130]
Hey !

While setting up LinOTP using the `pip install` method, I found that the latest version uploaded to PyPi is 2.10.0.1, which is exactly two years old in about 4 days.

Can you please update the PyPi repository or is there any particular reasoning to why it has not been updated ? Also, is there anything I can do to potentially help in updating the PyPi repository ?

Thanks !

**Comment by zsoltbarat** [comment]
Just can second this. And what about Python3?

**Comment by megfault** [comment]
Hi! I asked around, it looks like our team is already working on automating the upload to PyPi. I don't know the details, though.

**Comment by aneutron** [comment]
Hey @megfault ! Thanks a lot for answering. Could you please post some details on this thread about the timeframe when they're available  Once again, Thanks for answering !

**Comment by megfault** [comment]
Hi all, the [latest release of LinOTP is now available on PyPI](https://pypi.org/project/LinOTP/)! It also seems it will now be easier to keep the repository up-to-date. :sun_with_face:
