### ISSUE TITLE
Does A PIN contain any special characters ?

### ISSUE THREAD

**Issue by luckydogxf** [LinOTP/LinOTP#131]
Interesting thing is that when I used A PIN contains speical character `#` , it always returned 

curl -k 'https://172.16.106.6/validate/check?user=31000013&pass=Abc#123884384'
----------------------------
{
   "version": "LinOTP 2.10.1.1",
   "jsonrpc": "2.0802",
   "result": {
      "status": true,
      "value": false
   },
   "id": 0
}
-------------------------------
When I changed PIN to `Abc!123`, it was OK.

According to [http://linotp.org/doc/2.6/part-management/policy/selfservice.html](url), I didn't set any policy about PIN. 

Any idea ? 

Guess `#` was specially treated before it was encoded and inserted to Database.

**Comment by luckydogxf** [comment]
I did a further test,  PIN contains either `#` or `&` do not work, either.

while `!@$%*` work.

**Comment by luckydogxf** [comment]
Any chance that  I caught a bug? I'm glad to reproduce this issue for you if you want to do a further investigation.

**Comment by lukengda** [comment]
Make sure to properly encode characters for url parameters. `#` and `&` are used in URLs to separate specific segments. This applies to both GET and POST params submitted in form-urlencoded content type. You can inspect Set Pin requests in SelfService and Manage for examples.

**Comment by luckydogxf** [comment]
Oh, thanks for your informative reply. That quit helps.

So anything specail that do I have to setup to bypass this pitfall ? User may set his/her password with `#` or `&`.

**Comment by lukengda** [comment]
LinOTP SelfService and LinOTP Manage-UI both correctly encode the parameters. You can find tons of information online how to encode the pin on the data level and in the framework you are using. You are on your own now, but you can debug what we are doing in our applications.
