### ISSUE TITLE
HTTP Cookie expiry date is badly formatted leading to potential problems in login

### ISSUE THREAD

**Issue by aneutron** [LinOTP/LinOTP#136]
Hey :)

While debugging a problem with our LinOTP instance, I was surprised to see that LinOTP does not use a pre-made facility for session management.

There is however a problem with the way `Expires` is formatted, as it doesn't respect the HTTP RFC. This in turns creates a problem where the browser does a _best effort_ try which sometimes (in very recent versions of chromium), results in outdated cookies at issuance. 

The RFC defines a grammar [[1](https://tools.ietf.org/html/rfc6265#section-5.1.1)] for this, but in practice [[2](https://tools.ietf.org/html/rfc7234#section-5.3)][[3](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Permanent_cookies)], it boils down to using: 
```
%a, %d %b %Y %H:%M:%S GMT
``` 
instead of:
```
%Y-%m-%d %H:%M:%S
``` 
as is the case in the following code:

https://github.com/LinOTP/LinOTP/blob/5ae241dcc5e224b17fbc9aac1988bd0524879ed0/linotpd/src/linotp/lib/userservice.py#L80

I believe that this will solve @danieldjewell's problem that he referenced in issue #84.

**Comment by megfault** [comment]
Thanks for the report. We are looking into it.

**Comment by lukengda** [comment]
this should be fixed with the commit pushed on Apr 15, closing the issue.
