### ISSUE TITLE
NO_PUBKEY 913DFF12F86258E5

### ISSUE THREAD

**Issue by MICE07** [LinOTP/LinOTP#141]
I received the following error, and can this be fixed?

sudo apt update
W: GPG error: http://www.linotp.org/apt/debian buster Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 913DFF12F86258E5
E: The repository 'http://www.linotp.org/apt/debian buster Release' is not signed.

sudo apt-key adv --recv-keys 913DFF12F86258E5
Executing: /tmp/apt-key-gpghome.UnNsbtvHGV/gpg.1.sh --recv-keys 913DFF12F86258E5
gpg: key 913DFF12F86258E5: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1

~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

~$ uname -mrs
Linux 4.19.0-9-amd64 x86_64

**Comment by lukengda** [comment]
I could not discover anything wrong with the current repositories. You can use the following command to retrieve the signing key:
```
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys 913DFF12F86258E5
```
