### ISSUE TITLE
API and script

### ISSUE THREAD

**Issue by beren41** [LinOTP/LinOTP#142]
Hi. I had this idea. 3 to configure the linotp server. B create tokens using a python script that connects to the linotp api. In other words , you will end up with 3 independent databases on each linotp, but with the same tokens. If possible, any help =)

**Comment by lukengda** [comment]
This doesn't look like a problem of LinOTP itself, closing this issue here as we can't help you with your implementation. It is not the job of LinOTP to keep databases in sync.
