### ISSUE TITLE
E-Mail Challenge-Response not being changed

### ISSUE THREAD

**Issue by bender93** [LinOTP/LinOTP#143]
Hi,

I'm trying to change the default challenge-response ('e-mail sent successfully') for an e-mail OTP. I have tried with the API with the following call:

https://<LinOTP>/system/setConfig?session=<COOKIE>&EMAIL_CHALLENGE_PROMPT=<My Prompt>

I have also tried this:

https://<LinOTP>/system/setConfig?session=<COOKIE>&E-MAIL_CHALLENGE_PROMPT=<My Prompt>

But I continue receiving the default 'e-mail sent successfully'.

Please help!

**Comment by lukengda** [comment]
LinOTP does not support changing the "CHALLENGE_PROMPT" string in the validate API for SMS or Email tokens. You need to change that in the application calling the API or change the text in the source code of LinOTP for now.

**Comment by lukengda** [comment]
Closing this Github issue because it is not an issue of LinOTP, but the connected application that does the user interface.

**Comment by moonfriend** [comment]
Announcement: This is gonna be solved in the upcomming version 3.2.
