### ISSUE TITLE
The Dockerfile in /LinOTP/linotpd/src is completely broken

### ISSUE THREAD

**Issue by dcacklam** [LinOTP/LinOTP#161]
Attempting to build the dockerfile results in a failure due to a msising /opt/linotpd/apt folder on the image

As far as I can tell, that folder is supposed to contain locally built .deb files for linotp and linotp-selfservice

Nothing in the dockerfile or in setup.py appears to create or populate this directory, nor to create a Packages file to turn it into an APT repo. 

This breaks the entire dockerfile.

**Comment by lukengda** [comment]
The Dockerfile is working as intended combined with the Makefile targets that ensure that the Debian package is built beforehand. Please note that the Dockerfile is only used in our CI setup to run automated tests in a containerized setup. The Dockerfile is not created to be used as a production setup at the moment.
