### ISSUE TITLE
Selfservice is not accepting logins - 

### ISSUE THREAD

**Issue by dcacklam** [LinOTP/LinOTP#162]
For v3.0 branch

Attempting a valid login to the selfservice portal gets 'Login successful' followed immediately by 'Your session timed out, please login again."

This happens in both Chrome & Firefox, with and without browser add-ons running.

Log data is as follows:
LDAP TLS: using cipher=Unknown
[checkPass] check password for user 'uid=UserName,ou=People,dc=myldap,dc=com' on LDAP server 'ldap://mysite.mycompany.com'
LDAP TLS: using cipher=Unknown
[checkPass] ldap bind for 'uid=UserName,ou=People,dc=myldap,dc=com' successful

mysite.mycompany.com:80 10.32.185.246 - - [22/Jun/2021:17:04:17 +0000] "GET /userservice/context?session=undefined HTTP/1.1" 401 603 "http://mysite.mycompany.com/selfservice/en/login?redirect=%2Flogin%3Fredirect%3D%252Ftokens" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"

**Comment by lukengda** [comment]
Hi @dcacklam, this looks like a browser or apache caching problem. The latest LinOTP releases correctly authenticate against LDAP and selfservice sessions work as intended.

We do offer enterprise support and professional services, so do not hesitate to contact us if you are interested: http://linotp.org/support.html.
