### ISSUE TITLE
Policy time format

### ISSUE THREAD

**Issue by lckrspirit** [LinOTP/LinOTP#163]
Hi, 

Which time format, i can be use in the my policy? - So that the policy is executed every 15 minutes.

Thanks.

**Comment by lukengda** [comment]
Hi @lckrspirit, the policies are not executed in an interval. Instead, they are checked whenever a web request needs to know the policy action information just in time. You can enter in cron format, when a policy should be valid. This way, you can set the policy to be only valid for some time frame, e.g. for specific week days (`* * * * 1-5`).
