### ISSUE TITLE
linotp.org ssl certificate is expired

### ISSUE THREAD

**Issue by enzo-g** [LinOTP/LinOTP#164]
Hi guys, sorry for that issue, but IDK how to contact the dev team in another manner. The current SSL certificate of the website https://www.linotp.org/ is apparently expired since Saturday, June 26, 2021.

I'm afraid that will scare some people! 

Thanks for your great work.

**Comment by lukengda** [comment]
Thanks for bringing this up, it should have been fixed already at the point that you have written the issue, but it takes some time for the browsers to recognise the new certificate. It should now be fixed for you!
