### ISSUE TITLE
JQuery 3.4.1 Vulnerability (<=3.5.0)

### ISSUE THREAD

**Issue by andurin** [LinOTP/LinOTP#176]
We have an issue with passing security scans due to below vulnerability:

Description
According to the self-reported version in the script, the version of JQuery hosted on the remote web server is greater than or equal to 1.2 and prior to 3.5.0. It is, therefore, affected by multiple cross site scripting vulnerabilities. ...

Synopsis
The remote web server is affected by multiple cross site scripting vulnerability.

Solution
Upgrade to JQuery version 3.5.0 or later.

**Comment by lukengda** [comment]
Thanks for bringing this up. We are working on this and will fix it for the next release.
