### ISSUE TITLE
Missing DEB for 2.12.5 release

### ISSUE THREAD

**Issue by andurin** [LinOTP/LinOTP#178]
Hi,

I used to install LinOTP by the debian packet from http://linotp.org/apt/debian/dists/buster/linotp/all/ but I'm missing the 2.12.5 deb packet.

Is it posible to create the deb file to get rid of the jquery based security issues?

Regards,
Hendrik

**Comment by megfault** [comment]
Hello Hendrik, I think it's there now :)

**Comment by andurin** [comment]
Indeed. Thanks for letting me now :)
