### ISSUE TITLE
RPM release for 2.12.5

### ISSUE THREAD

**Issue by tyabell** [LinOTP/LinOTP#181]
Will there be RPMs released for 2.12.5?

The latest in the repo is 2.11.2
https://linotp.org/rpm/el7/linotp/x86_64/Packages/?C=M;O=D

**Comment by lukengda** [comment]
Hi @tyabell, thank you for your patience. We have finally release 2.12.5 rpm on linotp.org. Please see https://linotp.org/download.html for the updated instructions.
