### ISSUE TITLE
Auth failed using email-token when authentication policy is not equal 0 (default)

### ISSUE THREAD

**Issue by khrustalev-rg** [LinOTP/LinOTP#183]
Hi there!

We have LinOTP 2.12.3 integrated with openvpn-server. Authentication configured directly via LinOTP web interface, using pam_linotp.
If we  change authentication policy to any value except 0, connection to openvpn-server with email-token fails.
First step: challenge creation and sending email work correct. 
On second step, when we enter PIN+OTP or only OTP - LinOTP-server trying to create another challenge and connection fails.

**Comment by lukengda** [comment]
Hi @khrustalev-rg i am not sure currently what the restrictions are using pam_linotp, but this sounds like a support issue that our support team could assist you setting up. If you are interested in more in-depth support, please contact our support team for a personalised offer that fits your needs: https://linotp.de/en/support.html

If you think that this is a regression and you've encountered a bug, we would need a better reproduction-description to localize the problem.
