### ISSUE TITLE
Does LINOTP have any users limitation?

### ISSUE THREAD

**Issue by tiendatdtvt** [LinOTP/LinOTP#186]
Hello Team,

I'm planning to deploy LINOTP for my production. I'm concerned about User Limitations in LINOTP. All worked well in my UAT system with a few users.
So, Does LINOTP have any users limitation?

Thank You,
Alex

**Comment by lukengda** [comment]
There is no hard limit. LinOTP can be scaled with multiple threads per instance. You can always deploy multiple instances of LinOTP and sync the databases or access a database cluster.

We could assist you further if you have a professional support subscription: https://linotp.de/support.html
