### ISSUE TITLE
Failcounter exceeded does not release

### ISSUE THREAD

**Issue by tiendatdtvt** [LinOTP/LinOTP#195]
Hello Team,

My user failed login exceeds the default value is 10 so LINOTP blocks the first authentication and does not reset the counter after a long time. In this issue, the user can not log on all the time except I manually reset the failure counter on the LINOTP.

Does anyone have a solution for this issue?

Thank You and Best Regards,
Dat

**Comment by lukengda** [comment]
Hi @tiendatdtvt this is a security feature. The user must either have a second token that is not yet blocked to reset the failcounter in the selfservice (if so configured) or you must reset the failcounter via the /admin api. The admin can manually do so in the /manage UI or you could reset the counter periodically via some form of regular api access like with a cron job.

You could increase the allowed failed logins by changing the value for an existing token or increase the default for new tokens. But this does not solve the problem of resetting the token if the limit is reached. Hopefully this makes it clear to you why the fail counter exists.

**Comment by tiendatdtvt** [comment]
Thank you for your reply.
I need to write the script to reset that counter in a specific period of time.

Thank You
