### ISSUE TITLE
Update from 2.12.5 to 3.2 - Database error 65537 while instantiating the CBC mode

### ISSUE THREAD

**Issue by chises** [LinOTP/LinOTP#205]
Hello,
we have LinOTP 2.12.5 installed with mariaDB on debian 10 with apt repositories. Everything is running without any issues. 
We want to Upgrade to LinOTP 3.2 So we replaced the repository with linotp describe [here](https://www.linotp.org/doc/latest/part-installation/server-installation/deb_install.html) and tried to update the application. That fails with the following message:
```
ERROR: Failed to upgrade database! ValueError('Error 65537 while instantiating the CBC mode') [in /usr/lib/python3/dist-packages/linotp/model/migrate.py:513]
Exception occured during database setup: ValueError('Error 65537 while instantiating the CBC mode')
Failed to create database: Error 65537 while instantiating the CBC mode
```
I am not sure where to troubleshoot. 

I also installed a complete new Server made a backup of the old one with _linotp-backup_ and imported the files (encKey and database backup) to the new server. After replacing the encKey in /etc/linotp we see the following messages: 
```
root@bss-s-otp01:/etc/linotp# sudo -u linotp linotp
Configuration loaded from /usr/share/linotp/linotp.cfg
Configuration loaded from /etc/linotp/linotp.cfg
Configuration loaded from /etc/linotp/conf.d/01-debian-database.cfg
Configuration loaded from /etc/linotp/conf.d/50-selfservice-site-redirect.cfg
CRITICAL: Database schema is not current, run `linotp init database`. [in /usr/lib/python3/dist-packages/linotp/model/__init__.py:200]
root@bss-s-otp01:/etc/linotp# sudo -u linotp linotp init database
Configuration loaded from /usr/share/linotp/linotp.cfg
Configuration loaded from /etc/linotp/linotp.cfg
Configuration loaded from /etc/linotp/conf.d/01-debian-database.cfg
Configuration loaded from /etc/linotp/conf.d/50-selfservice-site-redirect.cfg
WARNING: Database conversion step suggested!
Please run command:
 linotp admin fix-db-encoding [in /usr/lib/python3/dist-packages/linotp/model/migrate.py:677]
ERROR: Failed to upgrade database! ValueError('Error 65537 while instantiating the CBC mode') [in /usr/lib/python3/dist-packages/linotp/model/migrate.py:513]
Exception occured during database setup: ValueError('Error 65537 while instantiating the CBC mode')
Failed to create database: Error 65537 while instantiating the CBC mode
```
I am very grateful for any help!

**Comment by lukengda** [comment]
Hi @chises,

I'm sorry for the issue you're experiencing with the 3.2.0 release. The issue is specific to certain token types, and we're already working on a fix. We hope to have a new release available in our debian repositories in January, and we'll be sure to let you know when it's available here.


Best regards,
Lukas

**Comment by chises** [comment]
Thank you for this information. It is not a big problem because old LinOTP2 is working so far. So I am waiting for a release/fix in Q1 2023?! Thank you and have a greater day. Feel free to close this issue :)

**Comment by chises** [comment]
We removed the Yubico Tokens and the Upgrade is working. These tokens were only used by admins so they can recreate them if they want to.
