### ISSUE TITLE
Unable to set the Application Name

### ISSUE THREAD

**Issue by dastra** [LinOTP/LinOTP#21]
It would appear that we are unable to set the Application Name.  This is useful as it helps people with multiple tokens in an application distinguish one application from another.

**Comment by lse-mirko** [comment]
Hi,

which "Application Name" do you refer to?  Do you mean the description of the tokens? Which kind of token is affected?

Best regards,

Mirko Ahnert

**Comment by dastra** [comment]
Hi Mirko,

I'm not sure if I have the correct term for it, but it is the description
of the application for which the tokens are valid.

So, to give an example from Google Authenticator (illustrated by this
screenshot -
https://www.sterndata.com//wp-content/uploads/2015-01-22-11.46.35.png ) the
Application Name is what appears above the current token value - for
instance "Google" for the first entry

Kind Regards

Dan

**Comment by lse-mirko** [comment]
Hi Dan,

please try to set the application name via a policy with scope: enrollment, action: tokenlabel. For more detailed information please have a look at:

http://www.linotp.org/doc/latest/part-management/policy/enrollment.html#tokenlabels

Best Regards,

Mirko Ahnert

**Comment by dastra** [comment]
Hi Mirko,

I've taken a look, and I'm afraid that's not what we are looking for.  The
token label changes the text underneath the OTP in Google Authenticator -
in the first item from the screenshot (
https://www.sterndata.com//wp-content/uploads/2015-01-22-11.46.35.png) the
token label is "steve@sterndata.com".  We're wondering how to change the
application name which appears _above_ the OTP - in the example give
"Google"

Kind Regards

Dan

**Comment by giobbe** [comment]
Hello Mirko,
you can try those patches:
https://github.com/lucab/LinOTP/commit/b32aad4883da65901ca0098a44812cea43404b30
https://github.com/lucab/LinOTP/commit/d87d2d09999f7ebfb38a3f764276145749c28770

We tested them successfully on 2.7.1.x and to 2.7.2.

Unfortunately they have not been accepted yet by the LSE team.

**Comment by dastra** [comment]
Hi Alessandro

That looks exactly like what we're looking for - thanks very much!

@Mirko - do you think the patches will be accepted?

Kind Regards

Dan

**Comment by lse-mirko** [comment]
Hi all,

we are working right now on the procedure for integrating patches in LinOTP and the related license questions. We will let you know when all necessary decisions are made and we can start merging pull requests.

Until then - thank you for your interest, contributions and patience so far. 

Kind Regards,

Mirko

**Comment by lucab** [comment]
PR #19 should address this, merge pending. I just rebased against current master, feedback/testing is welcome.

**Comment by lukengda** [comment]
This feature is implemented in LinOTP 2.9, i will therefore close this issue.
