### ISSUE TITLE
Possible to change the issuer of the TOTP qr-code?

### ISSUE THREAD

**Issue by corrugatedcardboard** [LinOTP/LinOTP#217]
Hi guys,

is it possible to change/customize the issuer in the generated qrcode, so that when I scan the qr code with my phone, instead of showing "LinOTP: 123456", it would show "QR-CODE FOR WEBSITE XXX: 123456"? 

Or is it not possible?

Thanks in advance!

**Comment by lukengda** [comment]
Please see the LinOTP documentation: https://www.linotp.org/doc/latest/part-management/policy/enrollment.html#token-issuer

You can configure the issuer and the label attributes. Thank you.
