### ISSUE TITLE
Unable to Access LinOTP Admin Interface on Port 8443

### ISSUE THREAD

**Issue by Linux-Alex** [LinOTP/LinOTP#226]
# Description
I followed the LinOTP installation tutorial on the official website ([link](https://www.linotp.org/doc/latest/part-installation/server-installation/login/admin-login.html)) to install LinOTP on Debian 10 (Buster). However, I am encountering an issue with accessing the LinOTP Admin Interface.

# Problem
I cannot access the LinOTP Admin Interface at https://127.0.0.1:8443/, and it seems like the port 8443 might not be open. I have tried the steps mentioned in the tutorial, and I also attempted the installation on a new virtual instance, but the problem persists.

# Steps to Reproduce
Followed the LinOTP installation tutorial on Debian 10 (Buster).
Attempted to access the LinOTP Admin Interface at https://127.0.0.1:8443/.

# Expected Behavior
I expect to be able to access the LinOTP Admin Interface without any issues following the provided tutorial ([link](https://www.linotp.org/doc/latest/part-installation/server-installation/login/admin-login.html)). Like on this image:
![manage_administrators](https://github.com/LinOTP/LinOTP/assets/37543086/b999577f-d6b2-4030-b999-b72866d581a8)

# Actual Behavior
I am unable to access the LinOTP Admin Interface at https://127.0.0.1:8443/. The port 8443 appears to be closed or inaccessible.

# Additional Information
LinOTP Version: LinOTP 3.2.5
Operating System: Debian 10 (Buster)
Database: mariadb-server (`sudo apt install mariadb-server`)
Steps Followed: 3.3.2. Installing from APT repositories (with problems on _3.3.3. LinOTP Administrators_)

# Reproducibility
The issue persists even after following the tutorial steps multiple times and attempting the installation on a new virtual instance.

# Screenshots
![Screenshot_20240129_231213](https://github.com/LinOTP/LinOTP/assets/37543086/28f9a1c5-b930-4ea9-81a7-781321d23d1b)

# Proposed Solution
I would appreciate assistance in resolving the issue and ensuring that the LinOTP Admin Interface is accessible on port 8443.

Thank you for your help.

**Comment by lukengda** [comment]
Hi @Linux-Alex, please note, that the :8443 administrative interface is part of the "LinOTP Smart Virtual Appliance" ([https://linotp.de/en/products/multi-factor-authentication/smart-virtual-appliance.html](https://linotp.de/en/products/multi-factor-authentication/smart-virtual-appliance.html)), that we provide to our customers with a support and subscription license for VM management. It is not directly part of LinOTP and not used to administrate LinOTP. Use /manage and the administrative APIs for that.
