### ISSUE TITLE
Configuration issue: No default realm defined. (realm.py)

### ISSUE THREAD

**Issue by MrSandvik** [LinOTP/LinOTP#230]
Acknowledging the fact that I am running on an unsanctioned platform: FreeBSD 14.1, I have seemingly successfully installed and configured LinOTP, using PostgreSQL as backend. I hope there is room for an issue;

I have created an admin user and set a password, but when I try logging in to the web interface, nothing happens. Checking the logs, I get an INFO generated by realm.py stating that there is a Configuration: issue: No default realm defined.

I have tried fiddling a bit with linotp.cfg and when I run 'linotp config show | grep REALM', I get this result:
Configuration loaded from /usr/local/etc/linotp/linotp.cfg
ADMIN_REALM_NAME=linotp_admins
DEFAULTREALM=linotp_admins

Any advice?

**Comment by lukengda** [comment]
Hi @MrSandvik - we usually do not provide support via github issues. We provide support service via https://linotp.de/en/support.html. However I'll try to give you a picture of what to look for.

DEFAULTREALM doesnt look like a supported LinOTP config. The warning that you get in the logs about a missing default realm is not preventing the login to /manage. It is only possible that you have a corrupt or wrongly configured database. A clean database, running "linotp init database", and adding the local-admin via CLI is all you need to do to get started:

```
linotp local-admins add <username>
linotp local-admins password <username>
```
