### ISSUE TITLE
Stupid question? Where is the configure webinterface?

### ISSUE THREAD

**Issue by ganzgustav22** [LinOTP/LinOTP#234]
There is /manage
There is /selfservice

According to this (kinda old) Howto, there is /config also.
https://kemptechnologies.com/blog/how-mfa-with-google-captcha

But it's not there. Where did it go?

**Comment by lukengda** [comment]
Hi @ganzgustav22, if you are referring to /config at port :8443, this is part of the Smart Virtual Appliance (SVA) which is part of our enterprise solution where we provide VM / host configuration (including the fully-automatic RADIUS configuration) (https://linotp.de/en/products/multi-factor-authentication/smart-virtual-appliance.html).

Coincidentally, we are currently replacing this interface with a modern management solution but :8443 is not phased out yet. If you are interested, reach out to our sales team for a trial: https://www.keyidentity.com/en/contact.html
