### ISSUE TITLE
Function returns a "sadface" smiley as a debug message

### ISSUE THREAD

**Issue by bradley-evans** [LinOTP/LinOTP#37]
<img width="475" alt="untitled" src="https://cloud.githubusercontent.com/assets/5460986/16966733/c207b25c-4dba-11e6-9e81-6b917fcacbdf.png">

**Comment by videlanicolas** [comment]
Yeap, LinOTP works that way.

The URI: /validate/simplecheck accepts GET variables user & pass, if it fails it gives you a sad face ( :-( ). If it's successfull it gives you a smiley face ( :-) ), and if there was a problem in your code (error reaching LDAP servers, exception in Python, couldn't open some file, etc...) it gives you a worried face ( :-/ ).

You can see this configuration on the Perl script that FreeRadius runs for each request.

**Comment by bradley-evans** [comment]
:-/

**Comment by lse-kay** [comment]
Yes :-) this is the intended short output to ease simple integration.
For more complex interaction, please use the /validate/check api - especially if you re using
the challenge response capabilities.
