### ISSUE TITLE
Cannot create a new policy from the command-line interface

### ISSUE THREAD

**Issue by bradley-evans** [LinOTP/LinOTP#40]
This may not be an intended use for linotpadm.py.

I was trying to provision my LinOTP instance using the following commands, executed from the shell:

`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=vagrant --command=setconfig --config=Policy.GoogleSelfService.action="webprovisionGOOGLE, webprovisionGOOGLEtime, "`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.client=""`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.realm="testrealm"`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.scope="selfservice"`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.time=""`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.user=""`
`/usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=[password]--command=setconfig --config=Policy.GoogleSelfservice.active=True`

If the policy does not already exist (as in if it's run against a policy that wasn't created in the web management interface) I get an error like so:

`[root@linotp ~]# /usr/bin/linotpadm.py --url=https://localhost:443 --admin=admin --password=vagrant --command=setconfig --config=Policy.GoogleSelfservice.client=""`

`Thank you for running the LinOTP2 linotpadmin client`

`{'Policy.GoogleSelfservice.client': ''}`
`Traceback (most recent call last):`
 `File "/usr/bin/linotpadm.py", line 829, in <module>`
`main()`
`File "/usr/bin/linotpadm.py", line 636, in main`
`r1 = lotpc.writeserverconfig(param)`
`File "/usr/lib/python2.7/site-packages/linotpadminclientcli/clientutils.py", line 478, in writeserverconfig`
`return self.connect('/system/setConfig', param)`
`File "/usr/lib/python2.7/site-packages/linotpadminclientcli/clientutils.py", line 380, in connect`
`raise LinOTPClientError(rv['result']['error']['code'], _("Your request to the LinOTP server was invalid: ") + rv['result']['error']['message'])`
`linotpadminclientcli.clientutils.LinOTPClientError: u"ERR-311: Your request to the LinOTP server was invalid: 'scope'"`

I'm running this on CentOS 7, trying to create a bash provisioner for the LinOTP authentication server. It is consistent about returning that the `scope` request is what is invalid.

**Comment by keyidentity-mirko** [comment]
Hi bradley-evans,

setting policies via the linotp-admin-cli is not recommend due to the complex nature of policies. Please use the /manage web interface or write a native python based management client using the LinOTP HTTP API instead.

Best regards,

Mirko
