### ISSUE TITLE
First verification of SMS challenge fails

### ISSUE THREAD

**Issue by nomennesc-io** [LinOTP/LinOTP#49]
I noticed validations of SMS OTP's failing on first attempt and then succeeding on second attempt.
After some debugging, I found out that the first failure is because of a call to Challenges.verify_checksum(ch) in lib/tokenclass.py failing.

It seems when the challenge for the SMS is created, a MAC is calculated based on data with the timestamp when the Challange was initialised in model/__init__.py. 
For example, I saw this data being passed to verfiyMessageSignature: {"timestamp": "2017-02-24 22:55:28", "challenge": "sms submitted", "session": {"status": "open"}, "tokenserial": "LSSM00028763", "received_tan": false, "transid": "201618721774", "data": {"valid_until": "2017-02-24 23:00:29.166714"}, "id": 23, "valid_tan": false}

However, when writing the challenge to the database, a new timestamp is written, resulting in the following entry in the challenges table:

| 23 | 201618721774 | {"valid_until": "2017-02-24 23:00:29.166714"} | sms submitted | {"status": "open", "mac": "a64938b3b12bd16e6cefa435522824bf50dddc7fdd6b8e462d4539045cef6938"} | LSSM00028763 | 2017-02-24 22:55:29 |              0 |            0 |         0 |

A subsequent attempt to validate the SMS OTP fails, because it calculates a MAC with the data {"timestamp": "2017-02-24 22:55:29", "challenge": "sms submitted", "session": {"status": "open"}, "tokenserial": "LSSM00028763", "received_tan": false, "transid": "201618721774", "data": {"valid_until": "2017-02-24 23:00:29.166714"}, "id": 23, "valid_tan": false}  - resulting in a different MAC.

**Comment by keyidentity-mirko** [comment]
Hi,

thank you very much for your observations and detailed analysis. We are looking into this issue. Could you please provide some more lines of a debug log and you configuration to speed up our investigation?

Best Regards,

Mirko

**Comment by nomennesc-io** [comment]
Hey Mirko,

First of all, the problem seems to be specific for a MySQL backend. We just switched to MariaDB and can no longer reproduce this behaviour.

As for some more lines of debug code, here are two lines showing the sending of an SMS and creation of the challenge in the database:

2017/02/23 - 14:22:40 DEBUG {140207367788288} [linotp.lib.tokens.smstoken][sendSMS #887] [sendSMS] submitMessage: u'303935', to phone u'0123456789'
2017/02/23 - 14:22:40 INFO  {140207367788288} [sqlalchemy.engine.base.Engine][_execute_context #915] ('{"valid_until": "2017-02-23 14:27:40.096543"}', 'sms submitted', '{"status": "open", "mac": "b75b8a53f0d6c91c45139a336c79852db97b97a944e22759bbd51734f327a3b3"}', 60L)

And here you see the subsequent validate call agreeing on the provided pass:

2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.HMAC][checkOtp #102] [checkOtp] calculating counter 16: u'303935' '303935'
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.HMAC][checkOtp #102] [checkOtp] calculating counter 16: u'303935' '303935'
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.hmactoken][checkOtp #381] [checkOtp] end. otp verification result was: res 16
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.hmactoken][checkOtp #381] [checkOtp] end. otp verification result was: res 16
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][isValid #812] [isValid] begin. check if challenge timeframe is still valid
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][isValid #812] [isValid] begin. check if challenge timeframe is still valid
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][getSMSInfo #776] [getSMSInfo] begin. get the sms token info
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][getSMSInfo #776] [getSMSInfo] begin. get the sms token info
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][getSMSInfo #783] [getSMSInfo] end. got the following token info: (phone:  u'0123456789', until: 1487856460)
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][getSMSInfo #783] [getSMSInfo] end. got the following token info: (phone:  u'0123456789', until: 1487856460)
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][isValid #823] [isValid] the sms challenge is still valid: ret: True
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][isValid #823] [isValid] the sms challenge is still valid: ret: True
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_auth_AutoSMSPolicy #2896] checking realms None
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_auth_AutoSMSPolicy #2896] checking realms None
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2510] [get_client_policy] with params {'action': 'autosms', 'scope': 'authentication', 'realm': u'ro'}, client '10.51.10.9' and user u'testuser-1234'
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2510] [get_client_policy] with params {'action': 'autosms', 'scope': 'authentication', 'realm': u'ro'}, client '10.51.10.9' and user u'testuser-1234'
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'autosms', 'scope': 'authentication', 'realm': u'ro'}
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'autosms', 'scope': 'authentication', 'realm': u'ro'}
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][checkOtp #668] [checkOtp] end. otp verification was successful! ret: 16
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokens.smstoken][checkOtp #668] [checkOtp] end. otp verification was successful! ret: 16

Skipping the policy checks, you can then see it succesfully passing checkPin and subsequently failing to auth:

2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.auth.validate][check_pin #130] [__checkToken] pin policy=0: checkin the PIN
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.auth.validate][check_pin #130] [__checkToken] pin policy=0: checkin the PIN
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokenclass][checkPin #1566] [checkPin] entering checkPin function
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokenclass][checkPin #1566] [checkPin] entering checkPin function
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.crypt][geturandom #636] geturandom()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.crypt][geturandom #636] geturandom()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.security.default][random #175] random()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.security.default][random #175] random()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.crypt][hash #403] hash()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.crypt][hash #403] hash()
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokenclass][checkPin #1587] [checkPin] result True
2017/02/23 - 14:22:47 DEBUG {140207468500736} [linotp.lib.tokenclass][checkPin #1587] [checkPin] result True
2017/02/23 - 14:22:47 WARNI {140207468500736} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'testuser-1234'@u'ro' failed to auth.
2017/02/23 - 14:22:47 WARNI {140207468500736} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'testuser-1234'@u'ro' failed to auth.

Hope that helps!

**Comment by keyidentity-mirko** [comment]
Hi,

thank you for the prompt answer. Interesting to hear the database switch helped. On what operating system do you run LinOTP (and which version of LinOTP)?

Best Regards,

Mirko

**Comment by nomennesc-io** [comment]
It's LinOTP-2.9.0.5-1.el7.x86_64 running on Centos7

**Comment by keyidentity-mirko** [comment]
Hi,

this seems to be caused by MySQL silently dropping data which do not fit into the cell definition while saving. Maybe MariaSQL is handling this differently? Anyhow - this problem has been addressed in LinOTP 2.9.1 by splitting data in to multiple cells.

Best Regards,

Mirko

**Comment by nomennesc-io** [comment]
Ok, great, we'll be upgrading to 2.9.1 and I'll report back if the problem somehow reoccurs. Thanks for the quick response!

**Comment by abinchy** [comment]
Hi Mirko,

I also have this issue where there is a high chance that the first authentication failed but always success the second attempt to validate the OTP. I realise that when I using the default SQLite in the linotp.ini, this issue is not happening. Is that an issue when using MYSQL database with LinOtp?

Besides, is there any documentation for the splitting data into multiple cells?

**Comment by satjak** [comment]
@abinchy  I had the same issue with my MYSQL database.
I found that the database was cold, and the request would fail because of a slow response to the first request. The second request would always work because the database warmed up.
If you find a smart way to fix this, please let me know. I picked the easy way to fix it, and just kept the database warm constantly.
