### ISSUE TITLE
Audit Trail signature identified as FAIL in a mysql master-master database.

### ISSUE THREAD

**Issue by sfoutrel** [LinOTP/LinOTP#54]
Hello,
I installed two linotp server 2.9.1.1 each with a mysql backend. they use the exact same configuration and encKey.
I used your configuration guides and procedure to activate replication on one server then dumped the database, imported it on second server and activated a master-master configuration on mysql.
Each token creation is replicated and usable successfully.
But Audit Trail is showing logs coming from the other server as FAIL in the signature column.

Did I miss something or is normal ?
Why is it FAIL ?

Thanks

**Comment by keyidentity-mirko** [comment]
Hi,

it seems like the signing key is a different one on each LinOTP node. By default it should be 

/etc/linotp2/linotp.ini:

`linotpAudit.key.public = /etc/linotp2/public.pem`
`linotpAudit.key.private = /etc/linotp2/private.pem`

pointing to the same key on both machines.

Best Regards,

Mirko

**Comment by sfoutrel** [comment]
Ouch. 
Thanks for your rapid answer.. 
I've got a lot to rewrite in my puppet so :+1:
