### ISSUE TITLE
 Unknown provider class: Identifier was smsprovider.HttpSMSProvider.HttpSMSProvider

### ISSUE THREAD

**Issue by almalki** [LinOTP/LinOTP#60]
When I try to add a new HTTP SMS provider, I get this error:
`Unknown provider class: Identifier was smsprovider.HttpSMSProvider.HttpSMSProvider - ImportError('No module named smsprovider.HttpSMSProvider',) `

Running 2.9.1, the deb package on Ubuntu 14.04.

Thanks..

**Comment by keyidentity-mirko** [comment]
Hi almalki,

please check whether the package linotp-smsprovider is installed.

Best Regards,

Mirko

**Comment by almalki** [comment]
@keyidentity-mirko yes, this was the problem. The docs never mention any other deb package other than linotp. 
https://www.linotp.org/doc/latest/part-installation/server-installation/deb_install.html#ubuntu-12-04-14-04

I was trying to create a PR to update the docs but could not find it in any repo.

Thanks..
