### ISSUE TITLE
Is it possible to autoenroll Yubikeys using an ID pulled from LDAP?

### ISSUE THREAD

**Issue by gregharvey** [LinOTP/LinOTP#65]
Hi,

So we have all our Yubikey IDs in LDAP, using the schema provided here:
http://www.logix.cz/michal/devel/yubikey-ldap/

While it's *OK* to ask people to enrol their Yubikeys, it would be even better if they didn't have to. We have the information available, but I'm not sure how to write the necessary policies. I've picked over the docs and found some clues that indicate it might be possible, but I think I need some expert assistance!

Apparently I should be able to use `#yubiKeyId` in the context of policies to get that value from LDAP, but what I don't get is how to automatically generate tokens using that value as the Yubikey ID for all users, so we don't have to ask people to do it manually. Perhaps it's not possible?

Thanks,

Greg

**Comment by keyidentity-mirko** [comment]
Hi Greg,

I see two options:

1) Autoassignment

This is the probably most convenient way - the token are assigned automatically if used the first time.

https://www.linotp.org/doc/latest/part-management/policy/enrollment.html?highlight=autoassignment#auto-assignment

2) Assignment via API

If autoassignment is not an option you could extract the serial numbers from the AD and assign the tokens to the same user in LinOTP. An assignment call would look like this:

https://LINOTP/admin/assign?user=USERNAME&serial=SERIAL&realm=REALM&session=COOKIE

Best Regards,

Mirko

**Comment by gregharvey** [comment]
Hi Mirko,

Sorry for not replying, I hadn't seen the answer! Thanks for this, very useful. I'll have a play with autoassignment, looks good.

Thanks again!

Greg
