### ISSUE TITLE
Unlicensed error message when trying to https://x.x.x.x/manage

### ISSUE THREAD

**Issue by sanghyunpark2017** [LinOTP/LinOTP#66]
/var/log/linotp/linotp.log

otp auth is ok but,,,

1399 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key:  license
1400 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key:  license
1401 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
1402 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
1403 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.lib.support][parseSupportLicense #152] [parseSupportLicense] **Verification of support license failed!**
1404 **Support not available, your product is unlicensed**
1405 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.lib.support][parseSupportLicense #152] [parseSupportLicense] Verification of support license failed!
1406 Support not available, your product is unlicensed
1407 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.controllers.system][isSupportValid #1971] **[isSupportValid] failed verify support info:**
1408 **InvalidLicenseException(u'Support not available, your product is unlicensed',)**
1409 Traceback (most recent call last):
1410   File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 1957, in isSupportValid
1411     lic_info) = isSupportLicenseValid(licString)
1412   File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 230, in isSupportLicenseValid
1413     lic_dict, lic_sign = parseSupportLicense(licString)
1414   File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 153, in parseSupportLicense
1415     raise InvalidLicenseException(error, type='UNLICENSED')
1416 InvalidLicenseException: Support not available, your product is unlicensed
1417 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.controllers.system][isSupportValid #1971] [isSupportValid] failed verify support info:
1418 InvalidLicenseException(u'Support not available, your product is unlicensed',)
1419 Traceback (most recent call last):
1420   File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 1957, in isSupportValid
1421     lic_info) = isSupportLicenseValid(licString)
1422   File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 230, in isSupportLicenseValid
1423     lic_dict, lic_sign = parseSupportLicense(licString)
1424   File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 153, in parseSupportLicense
1425     raise InvalidLicenseException(error, type='UNLICENSED')
1426 InvalidLicenseException: Support not available, your product is unlicensed
1427 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.controllers.system][isSupportValid #1978] [isSupportValid] done
1428 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.controllers.system][isSupportValid #1978] [isSupportValid] done

**Comment by keyidentity-simon** [comment]
Hello sanghyunpark2017

since it is possible to purchase a support license for the LinOTP github version, these messages are only infos. You can ignore it.

best regards
Simon

**Comment by Paul-HIT** [comment]
> /var/log/linotp/linotp.log
> 
> otp auth is ok but,,,
> 
> 1399 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key: license
> 1400 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key: license
> 1401 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
> 1402 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
> 1403 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.lib.support][parseSupportLicense #152] [parseSupportLicense] **Verification of support license failed!**
> 1404 **Support not available, your product is unlicensed**
> 1405 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.lib.support][parseSupportLicense #152] [parseSupportLicense] Verification of support license failed!
> 1406 Support not available, your product is unlicensed
> 1407 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.controllers.system][isSupportValid #1971] **[isSupportValid] failed verify support info:**
> 1408 **InvalidLicenseException(u'Support not available, your product is unlicensed',)**
> 1409 Traceback (most recent call last):
> 1410 File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 1957, in isSupportValid
> 1411 lic_info) = isSupportLicenseValid(licString)
> 1412 File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 230, in isSupportLicenseValid
> 1413 lic_dict, lic_sign = parseSupportLicense(licString)
> 1414 File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 153, in parseSupportLicense
> 1415 raise InvalidLicenseException(error, type='UNLICENSED')
> 1416 InvalidLicenseException: Support not available, your product is unlicensed
> 1417 2017/09/05 - 13:20:13 ERROR {140449381607168} [linotp.controllers.system][isSupportValid #1971] [isSupportValid] failed verify support info:
> 1418 InvalidLicenseException(u'Support not available, your product is unlicensed',)
> 1419 Traceback (most recent call last):
> 1420 File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 1957, in isSupportValid
> 1421 lic_info) = isSupportLicenseValid(licString)
> 1422 File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 230, in isSupportLicenseValid
> 1423 lic_dict, lic_sign = parseSupportLicense(licString)
> 1424 File "/usr/lib/pymodules/python2.7/linotp/lib/support.py", line 153, in parseSupportLicense
> 1425 raise InvalidLicenseException(error, type='UNLICENSED')
> 1426 InvalidLicenseException: Support not available, your product is unlicensed
> 1427 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.controllers.system][isSupportValid #1978] [isSupportValid] done
> 1428 2017/09/05 - 13:20:13 DEBUG {140449381607168} [linotp.controllers.system][isSupportValid #1978] [isSupportValid] done

How do you solve the problem? Which URL did you purchase the licence ? Or you find other solutions ? Thanks

**Comment by lukengda** [comment]
See http://linotp.org/support.html for available support options. As @keyidentity-simon said, you can ignore these messages if you are running the open-source variant only without support.
