### ISSUE TITLE
Token auto assignment fail

### ISSUE THREAD

**Issue by Webserve** [LinOTP/LinOTP#67]
Situation:

- LDAP Resolver in combination with Microsoft active directory. 
- Search filter: "(memberOf=CN=GB_group,OU=GB,OU=Resources,OU=group,OU=Hi Anonymous,DC=john,DC=dere,DC=nl)"
- In the user view the user "webserve" isn’t shown. 

When i use "https://192.168.1.1/validate/simplecheck?user=webserve&pass=Welkom01&realm=test" linotp is creating a token for this user. I get the message: ":-( 7687678678 sms submitted"

This is not right. It looks like the validate is ignoring the ldap resolver search filter. 
In the policy auto enrollment with sms is enabled.

Bug or configuration issue ?

**Comment by Webserve** [comment]
The following options are off. 

Pass on user not found: |  
-- | --
Pass on user no token:

I tried to set the policy in combination with user / ldapresolver like:
https://www.linotp.org/doc/latest/part-management/policy/users-in-policies.html#users-in-policies 

But i still looks like the search filter is being ignored by the policies.

**Comment by satjak** [comment]
I have a search filter that looks like this
`SearchFilter: (sAMAccountName=*)(memberof=CN=VPNAccess,OU=Security Groups,DC=Contoso,DC=com)`

**Comment by Webserve** [comment]
The problem was the user filter.  There was only filtered on samaccountname. 

Fixed it by adding the group to the user filter.
