### ISSUE TITLE
Empty userlist in policy 'system' not supported!

### ISSUE THREAD

**Issue by nconder** [LinOTP/LinOTP#9]
Ubuntu 12.04 running from pip install.

It seems that when the system policy was created the user "admin" did not get added to the system policy user list. All functionality of the admin site is broken. 

Do you know of a work around for this issue?

POP up on log on:
We are sorry. An internal error occurred:
uncaught exception: Empty userlist in policy 'system' not supported!
in file:
in line:0
To go on, reload this web page.

Error on policy page:
Empty userlist in policy 'system' not supported!

linotp.log

2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.controllers.system][**before** #164] [**before**::u'getConfig'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.controllers.system][**before** #164] [**before**::u'getConfig'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

2015/04/10 - 10:09:08 ERROR {140267063891712} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.controllers.system][**before** #164] [**before**::u'getRealms'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.controllers.system][**before** #164] [**before**::u'getRealms'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

2015/04/10 - 10:09:21 ERROR {140267080677120} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

2015/04/10 - 10:09:21 INFO  {140267080677120} [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies] Evaluating policies for the user: admin
2015/04/10 - 10:09:21 INFO  {140267080677120} [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies] Evaluating policies for the user: admin
2015/04/10 - 10:09:21 INFO  {140267080677120} [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies] Evaluating policies for the user: admin
2015/04/10 - 10:09:21 INFO  {140267080677120} [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies] Evaluating policies for the user: admin
2015/04/10 - 10:09:21 WARNI {140267080677120} [useridresolver.LDAPIdResolver][loadConfig #865] [loadConfig] conversion of self.uidType: u'objectGUID' to str()
2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system' not supported!
2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.controllers.system][**before** #164] [**before**::u'policies_flexi'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.controllers.system][**before** #164] [**before**::u'policies_flexi'] exception Exception(u"Empty userlist in policy 'system' not supported!",)
2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

2015/04/10 - 10:09:23 ERROR {140267080677120} [linotp.controllers.system][**before** #165] [**before**] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line 143, in **before**
    checkPolicyPre('system', action)
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127, in checkPolicyPre
    auth = getAuthorization('system', actions[method])
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in getAuthorization
    'action': action})
  File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in getPolicy
    raise Exception("Empty userlist in policy '%s' not supported!" % polname)
Exception: Empty userlist in policy 'system' not supported!

**Comment by lse-kay** [comment]
Hi,

sorry for the late reply - the problem could be solved by passing
an * as wildcard for any user.

Best regards,

    Kay

Am 10.04.2015 um 17:24 schrieb nconder:
>
> Ubuntu 12.04 running from pip install.
>
> It seems that when the system policy was created the user "admin" did
> not get added to the system policy user list. All functionality of the
> admin site is broken.
>
> Do you know of a work around for this issue?
>
> POP up on log on:
> We are sorry. An internal error occurred:
> uncaught exception: Empty userlist in policy 'system' not supported!
> in file:
> in line:0
> To go on, reload this web page.
>
> Error on policy page:
> Empty userlist in policy 'system' not supported!
>
> linotp.log
>
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.controllers.system][*before* #164] [*before*::u'getConfig']
> exception Exception(u"Empty userlist in policy 'system' not supported!",)
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.controllers.system][*before* #164] [*before*::u'getConfig']
> exception Exception(u"Empty userlist in policy 'system' not supported!",)
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> 2015/04/10 - 10:09:08 ERROR {140267063891712}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.controllers.system][*before* #164] [*before*::u'getRealms']
> exception Exception(u"Empty userlist in policy 'system' not supported!",)
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.controllers.system][*before* #164] [*before*::u'getRealms']
> exception Exception(u"Empty userlist in policy 'system' not supported!",)
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> 2015/04/10 - 10:09:21 ERROR {140267080677120}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> 2015/04/10 - 10:09:21 INFO {140267080677120}
> [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies]
> Evaluating policies for the user: admin
> 2015/04/10 - 10:09:21 INFO {140267080677120}
> [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies]
> Evaluating policies for the user: admin
> 2015/04/10 - 10:09:21 INFO {140267080677120}
> [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies]
> Evaluating policies for the user: admin
> 2015/04/10 - 10:09:21 INFO {140267080677120}
> [linotp.lib.policy][getAdminPolicies #681] [getAdminPolicies]
> Evaluating policies for the user: admin
> 2015/04/10 - 10:09:21 WARNI {140267080677120}
> [useridresolver.LDAPIdResolver][loadConfig #865] [loadConfig]
> conversion of self.uidType: u'objectGUID' to str()
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.lib.policy][getPolicy #558] Empty userlist in policy 'system'
> not supported!
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.controllers.system][*before* #164]
> [*before*::u'policies_flexi'] exception Exception(u"Empty userlist in
> policy 'system' not supported!",)
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.controllers.system][*before* #164]
> [*before*::u'policies_flexi'] exception Exception(u"Empty userlist in
> policy 'system' not supported!",)
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> 2015/04/10 - 10:09:23 ERROR {140267080677120}
> [linotp.controllers.system][*before* #165] [*before*] Traceback (most
> recent call last):
> File "/usr/lib/pymodules/python2.7/linotp/controllers/system.py", line
> 143, in *before*
> checkPolicyPre('system', action)
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 2127,
> in checkPolicyPre
> auth = getAuthorization('system', actions[method])
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 754, in
> getAuthorization
> 'action': action})
> File "/usr/lib/pymodules/python2.7/linotp/lib/policy.py", line 559, in
> getPolicy
> raise Exception("Empty userlist in policy '%s' not supported!" % polname)
> Exception: Empty userlist in policy 'system' not supported!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LinOTP/LinOTP/issues/9>.
>

-- 
Kay Winkler (Software Development) <Kay.Winkler@lsexperts.de>       
Mobil: +49 1751 874 258, Phone: +49 6151 860 86 262, Fax: 299         

LSE Leading Security Experts GmbH, Postfach 100121, 64201 Darmstadt  
Geschäftsführer: Oliver Michel, Sven Walther, http://www.lsexperts.de  
Unternehmenssitz: Weiterstadt, Amtsgericht Darmstadt: HRB8649
